/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shishir
 */
import java.net.Proxy;
import java.net.ProxySelector;
import java.util.List;
import java.util.Iterator;
import java.net.URI;
import java.net.InetSocketAddress;
import javax.swing.JOptionPane;
public class ProxyConfigUI extends javax.swing.JDialog {

    /**
     * Creates new form ProxyConfigUI
     */
    private Proxy proxy=Proxy.NO_PROXY;
    private String hostName;
    private int port;
    ProxyConfigUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.hostName=addressTF.getText();
        this.port=Integer.parseInt(portTF.getText());
    }
    public Proxy getProxy(){
        return (proxyCheck.isSelected())?proxy:Proxy.NO_PROXY;
    }
    private void setProxyCheck(){
        proxyCheck.setSelected(true);
        setProxyAddress();
        setPort();
    }
    private void setProxyAddress(){
        addressTF.setText(hostName);
    }
    private void setPort(){
        portTF.setText(""+port);
    }
    //void setProxyType(Proxy proxy){}
    private void setProxy(){
        Proxy proxy=Proxy.NO_PROXY;
        String url="http://www.google.com/";
        List<Proxy> proxyList=null; 
        System.setProperty("java.net.useSystemProxies", "true");
        try{
            ProxySelector def=ProxySelector.getDefault();
            proxyList=def.select(new URI(url));
            if(proxyList!=null){
                for(Iterator<Proxy> itr=proxyList.iterator();itr.hasNext();){
                    proxy=itr.next();
                }
                InetSocketAddress address=(InetSocketAddress)proxy.address();
                if(address==null){
                    this.proxy=Proxy.NO_PROXY;
                    JOptionPane.showMessageDialog(rootPane, "Could not find any proxy configuration in Internet Explorer Settings", "Download Manager", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    this.proxy=proxy;
                    this.hostName=address.getHostName();
                    this.port=address.getPort();
                    setProxyCheck();
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    public boolean isUsingProxy(){
        return proxyCheck.isSelected();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        proxyCheck = new javax.swing.JCheckBox();
        proxyAdd = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        portTF = new javax.swing.JTextField();
        UNLabel = new javax.swing.JLabel();
        unTF = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passTF = new javax.swing.JTextField();
        okBut = new javax.swing.JButton();
        getProxy = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proxy Configurations/Settings");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Proxy Configurations");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose Settings"));

        proxyCheck.setText("Use Proxy");
        proxyCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                proxyCheckItemStateChanged(evt);
            }
        });

        proxyAdd.setText("Proxy Server Address");
        proxyAdd.setEnabled(false);

        portLabel.setText("Port");
        portLabel.setEnabled(false);

        addressTF.setEditable(false);
        addressTF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        addressTF.setText("127.0.0.1");

        portTF.setEditable(false);
        portTF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        portTF.setText("56630");

        UNLabel.setText("User Name");
        UNLabel.setEnabled(false);

        unTF.setEditable(false);

        passLabel.setText("Password");
        passLabel.setEnabled(false);

        passTF.setEditable(false);

        okBut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okBut.setText("OK");
        okBut.setBorderPainted(false);
        okBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proxyCheck)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proxyAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(addressTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(portTF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(portLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unTF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UNLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passLabel)
                            .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(okBut, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proxyCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proxyAdd)
                    .addComponent(portLabel)
                    .addComponent(UNLabel)
                    .addComponent(passLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(okBut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getProxy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getProxy.setText("Get From IE");
        getProxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getProxyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getProxy, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(getProxy, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proxyCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_proxyCheckItemStateChanged
        if(proxyCheck.isSelected()){
            passLabel.setEnabled(true);
            proxyAdd.setEnabled(true);
            portLabel.setEnabled(true);
            UNLabel.setEnabled(true);
        }
        else{
            passLabel.setEnabled(false);
            proxyAdd.setEnabled(false);
            portLabel.setEnabled(false);
            UNLabel.setEnabled(false);
        }
    }//GEN-LAST:event_proxyCheckItemStateChanged

    private void getProxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getProxyActionPerformed
        setProxy();
    }//GEN-LAST:event_getProxyActionPerformed

    private void okButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UNLabel;
    private javax.swing.JTextField addressTF;
    private javax.swing.JButton getProxy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton okBut;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passTF;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTF;
    private javax.swing.JLabel proxyAdd;
    private javax.swing.JCheckBox proxyCheck;
    private javax.swing.JTextField unTF;
    // End of variables declaration//GEN-END:variables
}
